/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": process.env.NEXT_PUBLIC_AWS_PROJECT_REGION,
    "aws_appsync_graphqlEndpoint": process.env.NEXT_PUBLIC_AWS_APPSYNC_GRAPHQLENDPOINT,
    "aws_appsync_region": process.env.NEXT_PUBLIC_AWS_APPSYNC_REGION,
    "aws_appsync_authenticationType": process.env.NEXT_PUBLIC_AWS_APPSYNC_AUTHENTICATIONTYPE,
    "aws_appsync_apiKey": process.env.NEXT_PUBLIC_AWS_APPSYNC_APIKEY,
    "aws_cognito_identity_pool_id": process.env.NEXT_PUBLIC_AWS_COGNITO_IDENTITY_POOL_ID,
    "aws_cognito_region": process.env.NEXT_PUBLIC_AWS_COGNITO_REGION,
    "aws_user_pools_id": process.env.NEXT_PUBLIC_AWS_USER_POOLS_ID,
    "aws_user_pools_web_client_id": process.env.NEXT_PUBLIC_AWS_USER_POOLS_WEB_CLIENT_ID,
    // "aws_project_region": "us-east-1",
    // "aws_appsync_graphqlEndpoint": "https://jbdqrleio5bi5cre7y5fbl326e.appsync-api.us-east-1.amazonaws.com/graphql",
    // "aws_appsync_region": "us-east-1",
    // "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    // "aws_appsync_apiKey": "da2-tdgzyoe77nentmo23gdpdwwu4u",
    // "aws_cognito_identity_pool_id": "us-east-1:309f27bd-90cf-4e17-a987-a6a3dff59290",
    // "aws_cognito_region": "us-east-1",
    // "aws_user_pools_id": "us-east-1_czTA0SxqB",
    // "aws_user_pools_web_client_id": "7f4qmoghg43g8bmd5l6r42ucaf",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};

export default awsmobile;
